popup_type = "login_form"

data = {
  title = "Hello World",
  subtitle = "Lorem",
  message = "Quis qui ullamco cillum magna enim qui in. Deserunt sunt laborum laboris nulla ex officia nisi eiusmod duis sunt non. Voluptate velit id ea ea et duis culpa. Proident elit ut labore aliquip amet.",
  button = "Lorem Ipsum",
  showcase_image = "https://image.flaticon.com/icons/svg/214/214316.svg",
  deny_msg = "No Thanks"
}

id = "some_unique_id"

