# Pop up model for popup theme information
description = "Popup"
fields = {
  name = {
    type = "string"
  },
  title = {
    type = "string"
  },
  subtitle = {
    type = "string"
  },
  message = {
    type = "string"
  },
  image_url = {
    type = "string"
  },
  cancel_message = {
    type = "string"
  },
  popup_button = {
    type = "uuid"
  },
  shade = {
    type = "string"
  },
  submit_button_text = {
    type = "string"
  }
}
